name: Deploy to pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set API key environment variable
        run: |
          echo "API_KEY=$API_KEY" >> $GITHUB_ENV
      - name: Run JavaScript code
        run: |
          node ./static/js/api.js
